-- MySQL Script generated by MySQL Workbench
-- Thu Nov 19 01:10:32 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema justq
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema justq
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `justq` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `justq` ;

-- -----------------------------------------------------
-- Table `justq`.`sampledt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `justq`.`sampledt` (
  `OrderDate` DATE NULL DEFAULT NULL,
  `Region` VARCHAR(45) NULL DEFAULT NULL,
  `Rep` VARCHAR(45) NULL DEFAULT NULL,
  `Item` VARCHAR(45) NULL DEFAULT NULL,
  `Unit` BIGINT NULL DEFAULT NULL,
  `UnitCost` DECIMAL(10,2) NULL DEFAULT NULL,
  `EastRegulation` VARCHAR(1) NULL DEFAULT NULL,
  `Total` DECIMAL(10,2) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = '샘플데이터테이블';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
